# Generated by Django 4.2.7 on 2023-11-07 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='important',
            new_name='importante',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='title',
            new_name='titulo',
        ),
    ]
